export const STR = Object.freeze({
    PAGE_TITLE: "Barefeed",
    PAGE_SUBTITLE: "A simple feed reader for podcasts. No registration. No cookies.",
    URL_HINT: "For example: https://rss.art19.com/masters-of-scale",
    URL_LABEL: "Enter feed URL",
    URL_LABEL_FIRST: "Enter your first feed URL",
    BTN_ADD_FEED: "Add Feeds",
    BTN_ADD_YES: "Save",
    BTN_ADD_NO: "Cancel",
    BTN_DELETE_NO: "No, keep",
    BTN_DELETE_YES: "Yes, delete",
    BTN_CLOSE: "Close",
    BTN_DOWNLOAD: "Download Podcast",
    SEARCH: "Search this channel",
    NO_DATA: "Sorry, nothing to display here :(",
    CHANNELS: "Your Channels",
    ERR_FILE_TOO_BIG: "File size must be under 512 KB.",
    ERR_FILE_TOO_LONG: "Can not load more than 30 Lines.",
    ERR_LINE_TOO_LONG: "A line must not contain more than 2000 characters. Line is too long.",
    ERR_NOT_URL: "Invalid URL.",
    DESCR_ADD_MULTI: `You can add multiple feeds by uploading a text file containing a list of valid feed URLs. Each line must contain a feed URL. Existing feeds are ignored, valid new feeds are added. Download your current feeds to see the expected file structure.`,
});